### ISSUE TITLE
Не  работает на свежих  версиях  python 

### ISSUE THREAD

**Issue by AlexeyTorch** [igroykt/letsencrypt-nic#9]
проверял  на  Freebsd 14.0 Python 3.9.18
после запуска main -a запомниает логин, пароль приложения, а при запуске  выдает:
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Hook '--manual-auth-hook' for XXXXXX.ru reported error code 1
Hook '--manual-auth-hook' for XXXXXX.ru ran with error output:
 DnsApi error: __init__() missing 1 required positional argument: 'app_password'
1 renew failure(s), 0 parse failure(s)
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
```

При сборке  на Debian 12, Python 3.11.2  запускаю ./main -a

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/cx_Freeze/initscripts/__startup__.py", line 124, in run
    module_init.run(name + "__main__")
  File "/usr/local/lib/python3.11/dist-packages/cx_Freeze/initscripts/console.py", line 16, in run
    exec(code, module_main.__dict__)
  File "main.py", line 7, in <module>
  File "/root/letsencrypt-nic-dev/func/__init__.py", line 1, in <module>
    from .func import Func
  File "/root/letsencrypt-nic-dev/func/func.py", line 14, in <module>
    from cryptography.fernet import Fernet
  File "/usr/lib/python3/dist-packages/cryptography/fernet.py", line 14, in <module>
    from cryptography.hazmat.primitives import hashes, padding
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/padding.py", line 11, in <module>
    from cryptography.hazmat.bindings._rust import (
ImportError: cannot import name 'check_ansix923_padding' from 'cryptography.hazmat.bindings._rust' (unknown location)

```

**Comment by igroykt** [comment]
@AlexeyTorch приветствую. у меня пока нет времени заняться проектом. попробуй склонировать ветку dev. а вообще похоже что проблемы с пакетом cryptography, хотя обычно проблемы всплывают с patchelf.

**Comment by AlexeyTorch** [comment]
> @AlexeyTorch приветствую. у меня пока нет времени заняться проектом. попробуй склонировать ветку dev. а вообще похоже что проблемы с пакетом cryptography, хотя обычно проблемы всплывают с patchelf.

На Freebsd пробовал dev.
не помогло.
НА выходных  попробую сбросить пароль приложения, проверить не в этом ли дело.
но все равно спасибо.

**Comment by AlexeyTorch** [comment]
setup.py  
25 строку исправить с
    "packages": ["nic_api", "dns.resolver", "tld", "cryptography", "argparse", "slack_webhook", "telegram"],
на 
    "packages": ["nic_api", "dns.resolver", "tld", "cryptography", "argparse", "slack_webhook", "telegram"]
26 удалить

но я пока поставил acme.sh там есть поддержка nic.ru

**Comment by SVG62** [comment]
Спасибо добрый человек, только в виртуальной среде завелось
linking /opt/letsencrypt-nic/build/exe.linux-x86_64-3.11/lib/libpython3.11.so -> libpython3.11.so.1.0
Compile completed!

**Comment by SVG62** [comment]
Билд прошел успешно, выполнил команду  $mv build/* $HOME/letsencrypt-nic, далее
вот такой вывод
┌──(svg㉿svgserv)-[~/letsencrypt-nic/exe.linux-x86_64-3.11]
└─$ main -a                                                                                                                                                           10 ⚙
Команда «main» не найдена. Возможно, вы имели в виду:
  command 'maim' from deb maim
  command 'man' from deb man-db
Try: sudo apt install <deb name>

**Comment by SVG62** [comment]
Структура папки
![тшс](https://github.com/igroykt/letsencrypt-nic/assets/11736398/a48db23c-cc13-4876-be29-4fa195d04a31)

**Comment by igroykt** [comment]
> Приветствую, а у меня да же и не билдится , подскажите что делать? Очень надо этот тупорылый nicru одалел ┌──(svg㉿svgserv)-[/opt/letsencrypt-nic] └─$ python setup.py build 1 ⨯ 10 ⚙ running build running build_exe error: build_exe option cannot be the same as build_base directory

Приветствую. Исправил и запушил в ветку dev.

**Comment by igroykt** [comment]
> Структура папки ![тшс](https://private-user-images.githubusercontent.com/11736398/313481206-a48db23c-cc13-4876-be29-4fa195d04a31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMTU5NjQsIm5iZiI6MTcxNDIxNTY2NCwicGF0aCI6Ii8xMTczNjM5OC8zMTM0ODEyMDYtYTQ4ZGIyM2MtY2MxMy00ODc2LWJlMjktNGZhMTk1ZDA0YTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDExMDEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNjczOWNmYTA1Njc2MDM2MzY0MDViNTA3MjE3MmI1YjFkMGNiZDgzZGJhOGRiZDEwOGY3OGFmN2Q1ZmY1NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bky4mQvv0MBI1Gjdm0pG22W1LIZD6eiF3SEK8MU65aM)

Надо указывать точку и слеш мол запускаю приложение с текущий директории: ./main -h

**Comment by igroykt** [comment]
> проверял на Freebsd 14.0 Python 3.9.18 после запуска main -a запомниает логин, пароль приложения, а при запуске выдает:
> 
> ```
> Saving debug log to /var/log/letsencrypt/letsencrypt.log
> Hook '--manual-auth-hook' for XXXXXX.ru reported error code 1
> Hook '--manual-auth-hook' for XXXXXX.ru ran with error output:
>  DnsApi error: __init__() missing 1 required positional argument: 'app_password'
> 1 renew failure(s), 0 parse failure(s)
> Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
> ```
> 
> При сборке на Debian 12, Python 3.11.2 запускаю ./main -a
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/dist-packages/cx_Freeze/initscripts/__startup__.py", line 124, in run
>     module_init.run(name + "__main__")
>   File "/usr/local/lib/python3.11/dist-packages/cx_Freeze/initscripts/console.py", line 16, in run
>     exec(code, module_main.__dict__)
>   File "main.py", line 7, in <module>
>   File "/root/letsencrypt-nic-dev/func/__init__.py", line 1, in <module>
>     from .func import Func
>   File "/root/letsencrypt-nic-dev/func/func.py", line 14, in <module>
>     from cryptography.fernet import Fernet
>   File "/usr/lib/python3/dist-packages/cryptography/fernet.py", line 14, in <module>
>     from cryptography.hazmat.primitives import hashes, padding
>   File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/padding.py", line 11, in <module>
>     from cryptography.hazmat.bindings._rust import (
> ImportError: cannot import name 'check_ansix923_padding' from 'cryptography.hazmat.bindings._rust' (unknown location)
> ```

Приветствую.
На фряхе 14 протестил - работает. Видимо брал с ветки master. Смержил ветку dev c master.
На дебиане у меня просто выскочила ошибка при компиляции поскольку не был установлен rust. Поставил последнюю стабильную и все завелось. Конкретно в твоем случае это похоже на баг описанный [здесь](https://community.letsencrypt.org/t/importerror-cannot-import-name-x509-from-cryptography-hazmat-bindings-rust/185882). Кажется в этом случае может помочь обновление пакетного менеджера:
`
pip3 install --upgrade pip
pip3 install -r requirements.txt
`

**Comment by aid2** [comment]
На Debian 12 такая ошибка сейчас, ветка dev:

root@debian12:/home/user/letsencrypt-nic-dev# /home/user/lets-nic/main -v -t
-= LetsEncrypt NIC =-
Preparing domain list...
[+] ACME Test: [ START ]
Traceback (most recent call last):
  File "/usr/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot==2.1.0', 'console_scripts', 'certbot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/certbot", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 6, in <module>
    from certbot._internal import main as internal_main
  File "/usr/lib/python3/dist-packages/certbot/_internal/main.py", line 19, in <module>
    import josepy as jose
  File "/usr/lib/python3/dist-packages/josepy/__init__.py", line 40, in <module>
    from josepy.json_util import (
  File "/usr/lib/python3/dist-packages/josepy/json_util.py", line 14, in <module>
    from OpenSSL import crypto
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1616, in <module>
    class X509StoreFlags:
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1635, in X509StoreFlags
    NOTIFY_POLICY: int = _lib.X509_V_FLAG_NOTIFY_POLICY
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'. Did you mean: 'X509_V_FLAG_EXPLICIT_POLICY'?

**Comment by aid2** [comment]
> На Debian 12 такая ошибка сейчас, ветка dev:
> 
> root@debian12:/home/user/letsencrypt-nic-dev# /home/user/lets-nic/main -v -t -= LetsEncrypt NIC =- Preparing domain list... [+] ACME Test: [ START ] Traceback (most recent call last): File "/usr/bin/certbot", line 33, in sys.exit(load_entry_point('certbot==2.1.0', 'console_scripts', 'certbot')()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/bin/certbot", line 25, in importlib_load_entry_point return next(matches).load() ^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/importlib/metadata/**init**.py", line 202, in load module = import_module(match.group('module')) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/importlib/**init**.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 1206, in _gcd_import File "", line 1178, in _find_and_load File "", line 1149, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "/usr/lib/python3/dist-packages/certbot/main.py", line 6, in from certbot._internal import main as internal_main File "/usr/lib/python3/dist-packages/certbot/_internal/main.py", line 19, in import josepy as jose File "/usr/lib/python3/dist-packages/josepy/**init**.py", line 40, in from josepy.json_util import ( File "/usr/lib/python3/dist-packages/josepy/json_util.py", line 14, in from OpenSSL import crypto File "/usr/lib/python3/dist-packages/OpenSSL/**init**.py", line 8, in from OpenSSL import SSL, crypto File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 19, in from OpenSSL.crypto import ( File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1616, in class X509StoreFlags: File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1635, in X509StoreFlags NOTIFY_POLICY: int = _lib.X509_V_FLAG_NOTIFY_POLICY ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'. Did you mean: 'X509_V_FLAG_EXPLICIT_POLICY'?

решается обновлением пайтона и пайпа и рестартом

В итоге запускается, но выдаёт ошибку, не пойму - на nic.ru не может зайти?

---
root@debian12:/home/user/lets-nic# ./main -v -n
-= LetsEncrypt NIC =-
Preparing domain list...
[+] ACME Run: [ START ]
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Requesting a certificate for zabbix.domain.ru
Performing the following challenges:
dns-01 challenge for zabbix.domain.ru
Running manual-auth-hook command: /home/user/lets-nic/auth
Hook '--manual-auth-hook' for zabbix.domain.ru reported error code 1
Hook '--manual-auth-hook' for zabbix.domain.ru ran with error output:
 api.add_record error: Service not found
Hook '--manual-auth-hook' for zabbix.domain.ru ran with output:
Obtain token...
Waiting for verification...
Challenge failed for domain zabbix.domain.ru
dns-01 challenge for zabbix.domain.ru

Certbot failed to authenticate some domains (authenticator: manual). The Certificate Authority reported these problems:
Domain: zabbix.domain.ru
Type:   unauthorized
Detail: Incorrect TXT record "***********************" found at _acme-challenge.zabbix.domain.ru

Hint: The Certificate Authority failed to verify the DNS TXT records created by the --manual-auth-hook. Ensure that this hook is functioning correctly and that it waits a sufficient duration of time for DNS propagation. Refer to "certbot --help manual" and the Certbot User Guide.

Cleaning up challenges
Running manual-cleanup-hook command: /home/user/lets-nic/clean
Hook '--manual-cleanup-hook' for zabbix.domain.ru reported error code 1
Hook '--manual-cleanup-hook' for zabbix.domain.ru ran with error output:
 api.records error: Service not found
Hook '--manual-cleanup-hook' for zabbix.domain.ru ran with output:
Obtain token...
Extract all DNS records...
Some challenges have failed.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
---

**Comment by igroykt** [comment]
> > На Debian 12 такая ошибка сейчас, ветка dev:
> > root@debian12:/home/user/letsencrypt-nic-dev# /home/user/lets-nic/main -v -t -= LetsEncrypt NIC =- Preparing domain list... [+] ACME Test: [ START ] Traceback (most recent call last): File "/usr/bin/certbot", line 33, in sys.exit(load_entry_point('certbot==2.1.0', 'console_scripts', 'certbot')()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/bin/certbot", line 25, in importlib_load_entry_point return next(matches).load() ^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/importlib/metadata/**init**.py", line 202, in load module = import_module(match.group('module')) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/importlib/**init**.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 1206, in _gcd_import File "", line 1178, in _find_and_load File "", line 1149, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "/usr/lib/python3/dist-packages/certbot/main.py", line 6, in from certbot._internal import main as internal_main File "/usr/lib/python3/dist-packages/certbot/_internal/main.py", line 19, in import josepy as jose File "/usr/lib/python3/dist-packages/josepy/**init**.py", line 40, in from josepy.json_util import ( File "/usr/lib/python3/dist-packages/josepy/json_util.py", line 14, in from OpenSSL import crypto File "/usr/lib/python3/dist-packages/OpenSSL/**init**.py", line 8, in from OpenSSL import SSL, crypto File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 19, in from OpenSSL.crypto import ( File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1616, in class X509StoreFlags: File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1635, in X509StoreFlags NOTIFY_POLICY: int = _lib.X509_V_FLAG_NOTIFY_POLICY ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'. Did you mean: 'X509_V_FLAG_EXPLICIT_POLICY'?
> 
> решается обновлением пайтона и пайпа и рестартом
> 
> В итоге запускается, но выдаёт ошибку, не пойму - на nic.ru не может зайти?
> 
> root@debian12:/home/user/lets-nic# ./main -v -n -= LetsEncrypt NIC =- Preparing domain list... [+] ACME Run: [ START ] Saving debug log to /var/log/letsencrypt/letsencrypt.log Plugins selected: Authenticator manual, Installer None Requesting a certificate for zabbix.domain.ru Performing the following challenges: dns-01 challenge for zabbix.domain.ru Running manual-auth-hook command: /home/user/lets-nic/auth Hook '--manual-auth-hook' for zabbix.domain.ru reported error code 1 Hook '--manual-auth-hook' for zabbix.domain.ru ran with error output: api.add_record error: Service not found Hook '--manual-auth-hook' for zabbix.domain.ru ran with output: Obtain token... Waiting for verification... Challenge failed for domain zabbix.domain.ru dns-01 challenge for zabbix.domain.ru
> 
> Certbot failed to authenticate some domains (authenticator: manual). The Certificate Authority reported these problems: Domain: zabbix.domain.ru Type: unauthorized Detail: Incorrect TXT record "***********************" found at _acme-challenge.zabbix.domain.ru
> 
> Hint: The Certificate Authority failed to verify the DNS TXT records created by the --manual-auth-hook. Ensure that this hook is functioning correctly and that it waits a sufficient duration of time for DNS propagation. Refer to "certbot --help manual" and the Certbot User Guide.
> 
> ## Cleaning up challenges
> Running manual-cleanup-hook command: /home/user/lets-nic/clean
> Hook '--manual-cleanup-hook' for zabbix.domain.ru reported error code 1
> Hook '--manual-cleanup-hook' for zabbix.domain.ru ran with error output:
> api.records error: Service not found
> Hook '--manual-cleanup-hook' for zabbix.domain.ru ran with output:
> Obtain token...
> Extract all DNS records...
> Some challenges have failed.
> Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.

Приветствую.
Судя по всему не может найти SERVICE_ID. Оно указывается в nic.ru->услуги->dns-хостинг->столбец "услуги" прямо над кнопкой "управление dns-зонами".

**Comment by aid2** [comment]
2ygroykt Спасибо, вы правы - надо было указать ID, только не цифровой, а цифробуквенный. Нашёл, где вы подсказали. Однако снова что-то не проходит, ошибка " api.add_record error: DNS zone for domain ххх.ru not found".

Создал поддомен test.xxx.ru, в DNS на nic.ru есть А-запись, пингуется.

test  A  ххх.ххх.ххх.ххх

```
root@debian12:/home/user/lets-nic# ./main -v -n
-= LetsEncrypt NIC =-
Preparing domain list...
[+] ACME Run: [ START ]
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Requesting a certificate for test.xxx.ru
Performing the following challenges:
dns-01 challenge for test.xxx.ru
Running manual-auth-hook command: /home/user/lets-nic/auth
Hook '--manual-auth-hook' for test.xxx.ru reported error code 1
Hook '--manual-auth-hook' for test.xxx.ru ran with error output:
 api.add_record error: DNS zone for domain xxx.ru not found
Hook '--manual-auth-hook' for test.xxx.ru ran with output:
Obtain token...
Waiting for verification...
Challenge failed for domain test.xxx.ru
dns-01 challenge for test.xxx.ru

Certbot failed to authenticate some domains (authenticator: manual). The Certificate Authority reported these problems:
Domain: test.xxx.ru
Type:   dns
Detail: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.test.xxx.ru - check that a DNS record exists for this domain

Hint: The Certificate Authority failed to verify the DNS TXT records created by the --manual-auth-hook. Ensure that this hook is functioning correctly and that it waits a sufficient duration of time for DNS propagation. Refer to "certbot --help manual" and the Certbot User Guide.

Cleaning up challenges
Running manual-cleanup-hook command: /home/user/lets-nic/clean
Hook '--manual-cleanup-hook' for test.xxx.ru reported error code 1
Hook '--manual-cleanup-hook' for test.xxx.ru ran with error output:
 api.records error: DNS zone for domain xxx.ru not found
Hook '--manual-cleanup-hook' for test.xxx.ru ran with output:
Obtain token...
Extract all DNS records...
Some challenges have failed.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.

```

ЗЫ уже жалею, что затеял эту канитель на Debian, изначально хотел на фрюхе всё сделать, но в первую попытку очень много места съела установка rust, более 50Гб ...

**Comment by igroykt** [comment]
> 2ygroykt Спасибо, вы правы - надо было указать ID, только не цифровой, а цифробуквенный. Нашёл, где вы подсказали. Однако снова что-то не проходит, ошибка " api.add_record error: DNS zone for domain ххх.ru not found".
> 
> Создал поддомен test.xxx.ru, в DNS на nic.ru есть А-запись, пингуется.
> 
> test A ххх.ххх.ххх.ххх
> 
> ```
> root@debian12:/home/user/lets-nic# ./main -v -n
> -= LetsEncrypt NIC =-
> Preparing domain list...
> [+] ACME Run: [ START ]
> Saving debug log to /var/log/letsencrypt/letsencrypt.log
> Plugins selected: Authenticator manual, Installer None
> Requesting a certificate for test.xxx.ru
> Performing the following challenges:
> dns-01 challenge for test.xxx.ru
> Running manual-auth-hook command: /home/user/lets-nic/auth
> Hook '--manual-auth-hook' for test.xxx.ru reported error code 1
> Hook '--manual-auth-hook' for test.xxx.ru ran with error output:
>  api.add_record error: DNS zone for domain xxx.ru not found
> Hook '--manual-auth-hook' for test.xxx.ru ran with output:
> Obtain token...
> Waiting for verification...
> Challenge failed for domain test.xxx.ru
> dns-01 challenge for test.xxx.ru
> 
> Certbot failed to authenticate some domains (authenticator: manual). The Certificate Authority reported these problems:
> Domain: test.xxx.ru
> Type:   dns
> Detail: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.test.xxx.ru - check that a DNS record exists for this domain
> 
> Hint: The Certificate Authority failed to verify the DNS TXT records created by the --manual-auth-hook. Ensure that this hook is functioning correctly and that it waits a sufficient duration of time for DNS propagation. Refer to "certbot --help manual" and the Certbot User Guide.
> 
> Cleaning up challenges
> Running manual-cleanup-hook command: /home/user/lets-nic/clean
> Hook '--manual-cleanup-hook' for test.xxx.ru reported error code 1
> Hook '--manual-cleanup-hook' for test.xxx.ru ran with error output:
>  api.records error: DNS zone for domain xxx.ru not found
> Hook '--manual-cleanup-hook' for test.xxx.ru ran with output:
> Obtain token...
> Extract all DNS records...
> Some challenges have failed.
> Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
> ```
> 
> ЗЫ уже жалею, что затеял эту канитель на Debian, изначально хотел на фрюхе всё сделать, но в первую попытку очень много места съела установка rust, более 50Гб ...

Приветствую. Судя по ошибке сервера letsencrypt не могут отрезолвить созданную TXT запись. Понятное дело есть TTL записи потому в конфигурации по-умолчанию стоит гугловский публичный dns 8.8.8.8. Обычно когда гугловский dns начинает резолвить TXT запись, то к этому времени сервера letsencrypt тоже подхватывают изменения в зоне.
Также в ветке dev проводил рефакторинг с помощью chatgpt. Возможно ИИ запорола функцию проверки TXT записи.
Исходя из всего этого попробуй следующее:
1. проверь в config.ini прописан ли DNS_SERVER = 8.8.8.8 в секции [GENERAL] и попробуй еще раз
2. сделай бекап config.ini и собери с ветки master

P.S. также рекомендую использовать флаг -t поскольку количество попыток выписать сертификат у letsencrypt ограничено семью попытками в неделю (даже если фейлятся), а вот тестовый запуск можно использовать сколько угодно (флаг -n уже должен был создать аккаунт в letsencrypt, так что флаг -t уже должен работать).

**Comment by aid2** [comment]
> Приветствую. Судя по ошибке сервера letsencrypt не могут отрезолвить созданную TXT запись. Понятное дело есть TTL записи потому в конфигурации по-умолчанию стоит гугловский публичный dns 8.8.8.8. Обычно когда гугловский dns начинает резолвить TXT запись, то к этому времени сервера letsencrypt тоже подхватывают изменения в зоне.
> Также в ветке dev проводил рефакторинг с помощью chatgpt. Возможно ИИ запорола функцию проверки TXT записи.
> Исходя из всего этого попробуй следующее:
> 
> проверь в config.ini прописан ли DNS_SERVER = 8.8.8.8 в секции [GENERAL] и попробуй еще раз
> сделай бекап config.ini и собери с ветки master
> P.S. также рекомендую использовать флаг -t поскольку количество попыток выписать сертификат у letsencrypt ограничено семью попытками в неделю (даже если фейлятся), а вот тестовый запуск можно использовать сколько угодно.

начну с конца - 8.8.8.8 стоит с самого начала, естественно

пару дней назад брал именно master-ветку, с ней были ошибки. а с dev начало фурычить. когда был рефакторинг? недавно?

про -t как запускать в итоге? так?
./main -v -n -t

а теперь основное - ты пишешь про "созданную TXT запись". я посмотрел хистори на nic.ru, там ничего не создавалось твоим софт, ни разу(

**Comment by igroykt** [comment]
> > Приветствую. Судя по ошибке сервера letsencrypt не могут отрезолвить созданную TXT запись. Понятное дело есть TTL записи потому в конфигурации по-умолчанию стоит гугловский публичный dns 8.8.8.8. Обычно когда гугловский dns начинает резолвить TXT запись, то к этому времени сервера letsencrypt тоже подхватывают изменения в зоне.
> > Также в ветке dev проводил рефакторинг с помощью chatgpt. Возможно ИИ запорола функцию проверки TXT записи.
> > Исходя из всего этого попробуй следующее:
> > проверь в config.ini прописан ли DNS_SERVER = 8.8.8.8 в секции [GENERAL] и попробуй еще раз
> > сделай бекап config.ini и собери с ветки master
> > P.S. также рекомендую использовать флаг -t поскольку количество попыток выписать сертификат у letsencrypt ограничено семью попытками в неделю (даже если фейлятся), а вот тестовый запуск можно использовать сколько угодно.
> 
> начну с конца - 8.8.8.8 стоит с самого начала, естественно
> 
> пару дней назад брал именно master-ветку, с ней были ошибки. а с dev начало фурычить. когда был рефакторинг? недавно?
> 
> про -t как запускать в итоге? так? ./main -v -n -t
> 
> а теперь основное - ты пишешь про "созданную TXT запись". я посмотрел хистори на nic.ru, там ничего не создавалось твоим софт, ни разу(

Тестовый запуск: ./main -v -t

Рефакторинг был в последнем коммите.

Как вариант можно попробовать заменить в файле func/func.py функцию checkTXTRecord на этот (взято с мастера):
```  
    @classmethod
    def checkTXTRecord(self, DNS_SERVER, query_domain, test=False, verbose=False):
        try:
            count = len(DNS_SERVER)
            arr = []
            while True:
                for server in DNS_SERVER:
                    resolver = dns.resolver.Resolver(configure=False)
                    resolver.nameservers = [server]
                    if test:
                        resolver.resolve(query_domain, 'A')
                        return True
                    a = resolver.resolve(f'_acme-challenge.{query_domain}', 'txt')
                    arr.append(a.response.answer)
                if len(arr) == count:
                    break
                time.sleep(1)
            return True
        except Exception:
            pass
```

На debian 12 вроде собирал на чистой установке и все было норм 🤔 

P.S. надеюсь в конфиге в строке ZONE указан сперва xxx.ru, а потом уже *.xxx.ru? Иначе вроде тоже не работает.

**Comment by aid2** [comment]
сейчас так

ZONE = test.xxx.ru

**Comment by igroykt** [comment]
> сейчас так
> 
> ZONE = test.xxx.ru

Не не. Это норма для http-challenge, а dns-challenge выписывает wildcard сертификаты т.е. должно быть "ZONE = xxx.ru, *.xxx.ru", тогда выписанный сертификат будет покрывать любой поддомен (пример: test.xxx.ru, test2.xxx.ru, myblog.xxx.ru и т.д.). И да, основной домен тоже надо указывать даже если ему не нужен сертификат. Так уже работает letsencrypt.
Подводные камни тоже есть. Выписанный сертификат не подойдет к поддомену blabla.test.xxx.ru. Для этого надо добавить в ZONE еще одну запись *.test.xxx.ru. В целом думаю логика понятна.
Также выписанный на одном сервере сертификат возможно использовать и на других серверах, что достаточно удобно.

**Comment by aid2** [comment]
Заработало!!! подробности будут, большое спасибо!

**Comment by aid2** [comment]
Да, помог правильный конфиг:
ZONE = xxx.ru, *.xxx.ru
